services:
  # A Static Site services:
  - type: web
    name: junior-goat-website
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 3000
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: "0"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
